# Generated by Django 4.2.3 on 2024-08-13 06:55

import core.validators.company_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[core.validators.company_validators.validate_company_name]),
        ),
    ]
