# Generated by Django 4.2.3 on 2024-08-24 20:20

import core.validators.product_validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/allysondev/Área de Trabalho/VERIFICAÇÃO E VALIDAÇÃO DE SOFTWARE/Verificacao-e-Validacao/Verificacao-e-Validacao/catalog_project/media/images'), upload_to='images/', validators=[core.validators.product_validators.validate_image]),
        ),
    ]
