# Generated by Django 4.2.3 on 2024-08-04 17:21

import core.validators.category_validators
import core.validators.company_validators
import core.validators.user_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, validators=[core.validators.category_validators.validate_category_name]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, validators=[core.validators.company_validators.validate_company_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, validators=[core.validators.user_validators.validate_password]),
        ),
    ]
