# Generated by Django 4.2.3 on 2024-08-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
